# Generated by Django 4.2.30 on 2026-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
                ('password', models.CharField(max_length=128)),
                ('encrypted_key', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('year_of_admission', models.IntegerField()),
                ('membership', models.CharField(choices=[('S', 'Student'), ('L', 'Lecturer')], max_length=1)),
            ],
        ),
    ]
