# Generated by Django 4.2.30 on 2026-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_institution_studentprofile_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
