# Generated by Django 4.2.30 on 2026-10-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_department_head_module_lecture_coursematerial'),
        ('courses', '0002_lecture'),
    ]

    operations = [
    ]
