"""
serializers.py - DRF serializers for the Accounts app.

WHAT ARE SERIALIZERS?
Serializers convert between Python objects and JSON (and vice versa):
    - Serialization:   Python object → JSON  (for API responses)
    - Deserialization:  JSON → Python object  (for API requests)

Think of them as "forms for the API". Just like forms validate HTML input,
serializers validate JSON input from API requests.

FORMS vs SERIALIZERS:
    Forms       → for HTML templates (render HTML, validate form data)
    Serializers → for the REST API (render JSON, validate JSON data)

EXAMPLE API RESPONSE (using UserSerializer):
    GET /api/users/1/
    {
        "id": 1,
        "username": "john_doe",
        "email": "john@example.com",
        "first_name": "John",
        "last_name": "Doe",
        "role": "student",
        "phone": "08012345678",
        "date_of_birth": "2000-05-15"
    }

ModelSerializer auto-generates serializer fields from model fields,
just like ModelForm auto-generates form fields.
"""

from rest_framework import serializers  # DRF's serializer classes
from .models import User               # Our custom User model


class UserSerializer(serializers.ModelSerializer):
    """
    Serializes User objects to/from JSON.
    Used for reading user data (GET requests) and updating user data (PUT/PATCH requests).

    USED IN: API views (api/urls.py → viewsets)
    """
    class Meta:
        model = User  # This serializer works with User objects

        # Which fields to include in the JSON output
        # Notice: password is NOT here — we never send passwords in API responses
        fields = ["id", "username", "email", "first_name", "last_name", "role", "phone", "date_of_birth"]

        # read_only_fields: These fields can be read (GET) but not written (POST/PUT)
        # The "id" is auto-generated by the database — users shouldn't set it
        read_only_fields = ["id"]


class RegisterSerializer(serializers.ModelSerializer):
    """
    Serializes registration data from JSON.
    Used for creating new users via the API (POST /api/register/).

    The password field is write_only=True — it's accepted in requests
    but NEVER included in responses (for security).

    USED IN: API registration endpoint
    """
    # Explicit field definition overrides the auto-generated one from the model
    # write_only=True: accept this field in POST requests, but never return it in responses
    # min_length=8: password must be at least 8 characters
    password = serializers.CharField(write_only=True, min_length=8)

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "role", "password"]

    def create(self, validated_data):
        """
        Called when serializer.save() is called after successful validation.

        We use create_user() instead of create() because create_user():
            1. Hashes the password (create() would store it as plain text!)
            2. Sets is_active=True
            3. Normalizes the email

        **validated_data unpacks the dictionary:
            User.objects.create_user(username="john", email="john@example.com", password="secret123", ...)
        """
        return User.objects.create_user(**validated_data)
